/// Flutter icons CarClinicIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CarClinicIcons
///      fonts:
///       - asset: fonts/CarClinicIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CarClinicIcons {
  CarClinicIcons._();

  static const _kFontFam = 'CarClinicIcons';
  static const String? _kFontPkg = null;

  static const IconData group_309 =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_1 =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_user =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_319 =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
